targets:
  gen-db:
    program: sqlc
    args:
      - generate
  gen-ui:
    program: templ
    args:
      - generate
  postgres:
    program: docker
    args:
      - "run"
      - "-it"
      - "--rm"
      - "--name"
      - "urlshorter-postgres"
      - "-p"
      - "127.0.0.1:5432:5432"
      - "-e"
      - "POSTGRES_USER=urlshorter"
      - "-e"
      - "POSTGRES_PASSWORD=urlshorter"
      - "postgres:16-alpine"
  run-app:
    program: go
    args:
      - "run"
      - "."
    env:
      DB_URI: "postgres://urlshorter:urlshorter@127.0.0.1:5432/urlshorter?sslmode=disable"
      PUBLIC_URL: "http://localhost:8080"
